### PR TITLE
Add dashboards for AWS Transit Gateway and AWS Network Firewall

### PR DESCRIPTION
**Pull request by diego-ojeda-binbash**

### CODE REVIEW

**Comment by jangaraj** [comment]
Hi Diego,

Thank you for the contribution. Would it be possible to update descriptions and doc link in footers, please? They refer to VPN. Or I can update them later.

**Comment by diego-ojeda-binbash** [comment]
@jangaraj Whoops, sorry about that. I just fixed them. Could you check?

**Comment by jangaraj** [comment]
LGTM, thank you

**Comment by jangaraj** [comment]
Minor updates + Grafana.com exports:
- https://grafana.com/grafana/dashboards/14955
- https://grafana.com/grafana/dashboards/14954

Thank you again.

**Pull request merged**
