### PR TITLE
Creating AWS-eks cluster metrics json

### PR DESCRIPTION
**Pull request by ksanjay7**

### CODE REVIEW

**Comment by ksanjay7** [comment]
@jangaraj - Tests that PR is failing is expecting login for docker. Not sure where all I need to mention import of this file and to pass any credentails.

**Comment by jangaraj** [comment]
Please, ignore Ci test for now. Thank you for EKS dashboard. Unfortunately, I don't have any EKS with Container Insights, so I can't verify it. Could you paste some screenshot here and also add documentation footer text panel with link to https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html please?

**Comment by ksanjay7** [comment]
Added documentation and will do an additional check-in once I take screenshots from my personal account EKS.

**Comment by jangaraj** [comment]
Thanks. Dashboard updated and published https://grafana.com/grafana/dashboards/14392

**Pull request merged**
