### PR TITLE
aws-api-gateway: Improve $stage variable query

### PR DESCRIPTION
**Pull request by franciscocpg**
Improves the  `$stage` query by listing only existing stages in the selected `$apiname`.

### CODE REVIEW

**Comment by jangaraj** [comment]
Thank you, Francisco.

**Comment by dariagrudzien** [comment]
@franciscocpg @jangaraj Does this dashboard still work correctly for you? When I imported it, I saw these two errors:

Screen Shot 2021-05-21 at 20 08 30

I'm wondering whether it's caused by the issue with the dashboard, or some missing IAM policies. I've just added this statement to the policy used for Grafana (in addition to all statements for CloudWatch metrics):

```
            "Effect": "Allow",
            "Action": [
                "apigateway:GET"
            ],
            "Resource": "*"
```

But the error persists.

**Comment by jangaraj** [comment]
@dariagrudzien see readme:

> Please set your dashboard variables (Region, ...) after dashboard import. Empty dashboard variables are reason of initial "Unable to call AWS API" or "Metric request error" error.

Readme also contains IAM policy. You really don't need any `apigateway` permission, you need `cloudwatch` permissions.

**Comment by dariagrudzien** [comment]
@jangaraj Thank you for the confirmation 👍

**Pull request merged**
