### PR TITLE
Fix dimensions

### PR DESCRIPTION
**Pull request by dominikhahn**

### CODE REVIEW

**Comment by jangaraj** [comment]
Hi Dominik, thx for PR. 

Is there any reason to remove `UnHealthyHostCount, HealthyHostCount` metrics? They should be available (http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html). Also could you add some screenshot please (unfortunately, I don't have any app ELB)?

Thanks!

**Comment by dominikhahn** [comment]
Hi jangaraj

Here you go
aws-cloutwatch-appelb-metrics

**Comment by jangaraj** [comment]
OK. Could you commit also some screenshot of grafana dashboard, so users will see how dashboad looks like, please? Thx.

**Comment by dominikhahn** [comment]
Yes of course. FYI: i removed the region query (see screenshot)

aws-cloutwatch-appelb-dashboard

**Comment by jangaraj** [comment]
Thanks, merged and https://grafana.net/dashboards/650 updated.

**Comment by dominikhahn** [comment]
Great, thank you! Cheers

**Pull request merged**
